package com.example.brave_sailors.data.mapper

import com.example.brave_sailors.data.local.database.entity.SavedShip
import com.example.brave_sailors.data.local.database.entity.User
import com.google.firebase.database.DataSnapshot

// --- USER MAPPING ---

/*
 * Converts Local Data (User + Fleet) to a Cloud Map for Firebase upload.
 * This ensures all progression stats and the current fleet layout are synchronized.
 */
fun User.toCloudMap(fleet: List<SavedShip>): Map<String, Any?> {
    return mapOf(
        "id" to id,
        "email" to email,
        "name" to name,
        "googleName" to googleName,
        "googlePhotoUrl" to googlePhotoUrl,
        "countryCode" to countryCode,
        "lastUpdated" to System.currentTimeMillis(),

        // Progression & Stats
        "level" to level,
        "currentXp" to currentXp,
        "lastWinTimestamp" to lastWinTimestamp,
        "totalScore" to totalScore,
        "wins" to wins,
        "losses" to losses,
        "shipsDestroyed" to shipsDestroyed,
        "totalShotsFired" to totalShotsFired,
        "totalShotsHit" to totalShotsHit,

        // FLEET MAPPING
        // Converts the list of SavedShip objects into a list of Maps for Firebase storage
        "fleet" to fleet.map { ship ->
            mapOf(
                "shipId" to ship.shipId,
                "size" to ship.size,
                "row" to ship.row,
                "col" to ship.col,
                "isHorizontal" to ship.isHorizontal
            )
        }
    )
}

/*
 * Converts a Firebase DataSnapshot back into a User entity.
 * Note: The fleet data is ignored here as it is handled by toSavedShipList.
 */
fun DataSnapshot.toUserEntity(currentLocalUser: User?): User? {
    if (!this.exists()) return null
    val map = this.value as? Map<String, Any> ?: return null
    val uid = this.key ?: return null

    // Helper functions to safely parse Firebase data types
    fun getLong(key: String): Long = (map[key] as? Number)?.toLong() ?: 0L
    fun getInt(key: String): Int = (map[key] as? Number)?.toInt() ?: 0
    fun getString(key: String): String = (map[key] as? String) ?: ""
    fun getStringNullable(key: String): String? = map[key] as? String

    // Keep the local profile picture path if it points to internal storage,
    // otherwise use the URL from the cloud.
    val resolvedProfilePic = if (currentLocalUser?.profilePictureUrl?.startsWith("/") == true) {
        currentLocalUser.profilePictureUrl
    } else {
        getStringNullable("profilePictureUrl")
    }

    return User(
        id = uid,
        email = getString("email"),
        sessionToken = currentLocalUser?.sessionToken,
        name = getString("name").ifEmpty { "Sailor" },
        profilePictureUrl = resolvedProfilePic,
        googleName = getString("googleName"),
        googlePhotoUrl = getStringNullable("googlePhotoUrl"),
        countryCode = getStringNullable("countryCode"),
        lastUpdated = getLong("lastUpdated"),
        level = getInt("level"),
        currentXp = getInt("currentXp"),
        lastWinTimestamp = getLong("lastWinTimestamp"),
        totalScore = getLong("totalScore"),
        wins = getInt("wins"),
        losses = getInt("losses"),
        shipsDestroyed = getInt("shipsDestroyed"),
        totalShotsFired = getLong("totalShotsFired"),
        totalShotsHit = getLong("totalShotsHit")
    )
}

// --- FLEET MAPPING ---

/*
 * Extracts and maps the Fleet List from the Firebase DataSnapshot.
 */
fun DataSnapshot.toSavedShipList(userId: String): List<SavedShip> {
    val fleetList = mutableListOf<SavedShip>()

    // Navigate to the "fleet" child node within the user snapshot
    val fleetSnapshot = this.child("fleet")

    if (fleetSnapshot.exists()) {
        for (shipSnap in fleetSnapshot.children) {
            val map = shipSnap.value as? Map<String, Any> ?: continue

            val ship = SavedShip(
                // Note: The primary key 'id' is auto-generated by Room (0), so it's not synced
                userId = userId,
                shipId = (map["shipId"] as? Number)?.toInt() ?: 0,
                size = (map["size"] as? Number)?.toInt() ?: 0,
                row = (map["row"] as? Number)?.toInt() ?: 0,
                col = (map["col"] as? Number)?.toInt() ?: 0,
                isHorizontal = (map["isHorizontal"] as? Boolean) ?: true
            )
            fleetList.add(ship)
        }
    }
    return fleetList
}